name: belajar_app
description: "belajar dasar - dasar flutter yang terdiri dari splashscreen, auth (login & register), penggunaan main_page untuk navigasi ke beberapa halaman"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  english_words: ^4.0.0
  provider: ^6.1.2
  intl: ^0.20.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true